More robust bash script

diff --git a/run_autograder b/run_autograder
--- a/run_autograder
+++ b/run_autograder
@@ -1,19 +1,33 @@
 #!/usr/bin/env bash
 
+# This file shouldn't need to be modified
 # Set up autograder files
 
+# Go to our directory (our current root) in the autograder
 cd /autograder/source || exit 1
 
+# Get a list of required files by looking at config
 files_needed=$(python3 -c "
 from grader import Grader
 
 config = Grader.read_json('source', 'config.json')
-print(' '.join(config['files_needed']))
-")
+print('\n'.join(config['files_needed']))
+") || {
+# If it fails, just return early
+    echo "Error reading required files. Exiting."
+    exit 1
+}
 
+# For each file (seperated by a newline), copy it if present, otherwise just skip
+IFS=$'\n'
 for file in $files_needed; do
-    cp /autograder/submission/"$file" /autograder/source/"$file"
+    if [ -e "/autograder/submission/$file" ]; then
+        cp "/autograder/submission/$file" "/autograder/source/$file"
+    else
+        echo "Warning: $file not found in /autograder/submission."
+    fi
 done
 
+# Finally, grade this submission
 python3 run_tests.py
 python3 grader.py
